name: Update Movie Data

on:
schedule:
  # 每天 UTC 时间 02:00 运行 (北京时间 10:00)
  - cron: '0 2 * * *'
workflow_dispatch: # 允许手动触发
push:
  branches: [ main, master ]

jobs:
update-data:
  runs-on: ubuntu-latest
  
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'
      
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install requests
      
  - name: Run movie data fetcher
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    run: |
      python fetch_movie_data.py
      
  - name: Check if homepage.json changed
    id: verify-changed-files
    run: |
      if [ -n "$(git status --porcelain)" ]; then
        echo "changed=true" >> $GITHUB_OUTPUT
      else
        echo "changed=false" >> $GITHUB_OUTPUT
      fi
      
  - name: Commit and push changes
    if: steps.verify-changed-files.outputs.changed == 'true'
    run: |
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git add homepage.json
      git commit -m "Update movie data - $(date +'%Y-%m-%d %H:%M:%S')"
      git push
